# Generated by Django 2.0.5 on 2018-06-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecooked', '0002_auto_20180612_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iscook',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
