# Generated by Django 2.0.5 on 2018-06-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecooked', '0003_profile_iscook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iscook',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
