# Generated by Django 2.0.5 on 2018-06-12 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homecooked', '0004_auto_20180612_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('logo', models.ImageField(default='img/None/no-img.gif', upload_to='img/')),
                ('description', models.TextField(max_length=140)),
                ('iscook', models.CharField(blank=True, max_length=5)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/None/no-img.gif', upload_to='img/'),
        ),
    ]
