# Generated by Django 2.0.5 on 2018-06-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecooked', '0005_auto_20180612_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='iscook',
        ),
    ]
