# Generated by Django 2.0.5 on 2018-06-13 16:21

import builtins
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homecooked', '0006_auto_20180612_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('image', models.ImageField(default='img/None/no-img.gif', upload_to='img/')),
                ('description', models.TextField(max_length=140)),
                ('price', models.FloatField()),
                ('cousin_type', models.CharField(max_length=15)),
                ('dietary', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), size=None)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_by'],
            },
        ),
        migrations.AddField(
            model_name='kitchen',
            name='doesDeliver',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name=builtins.max),
        ),
        migrations.AddField(
            model_name='order',
            name='order_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_from', to='homecooked.Kitchen'),
        ),
        migrations.AddField(
            model_name='dish',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='homecooked.Kitchen'),
        ),
    ]
